### ISSUE TITLE
Tick World Crashing with Mo Creeps and Weirdos Revival

### ISSUE THREAD

**Issue by Desenrrollado** [Elite-Modding-Team/MoCreaturesExtended#1]
I know this is a modified fork of Almura's Mo Creature Branch. I'd originally sent an email to try to get in contact with the original creator ,and there wasn't really a reply to that end. So it was nice seeing it spring back to life.

That it's barely been released, and is gonna have a multitude of issues. I however am always curious and like testing for issues. I appreciate the work you and the community do heavily. It's really nice to see the progress and contribution. However I was curious as within yesterday and today's current build. I've hit similar crashes. This one was upon world generation and loading. It just stopped. I assume it has to do with the world Generation. But I'm not too knowledgeable.

Thank you so much, and sorry to bother you with this. I know you guys have a lot of work to do, but I at least figured I could post this in advance. Maybe you already know. Have a good rest of your day, afternoon, evening or night.

Log:
[latest.log](https://github.com/ACGaming/MoCreaturesExtended/files/11446339/latest.log)

Crash Report: 
[crash-2023-05-10_15.47.37-server.txt](https://github.com/ACGaming/MoCreaturesExtended/files/11446340/crash-2023-05-10_15.47.37-server.txt)

Edit: From additional testing I gather it's more likely to do with Mo Creeps and Weirdos Revival. Which is sad since I'm used to them going hand in hand. I understand if not much can be done to really fix them. As certain mods just are incompatible with one another. Though, thank you and sorry for taking up your time.

**Comment by ACGaming** [comment]
Can‘t reproduce with using only Mo‘ Creatures Extended and More Creeps And Weirdos Revival. Did you disable some of its mobs?
Either way, since I suspect spawn weights of 0 being the culprit here, the latest commit contains extra handling for this.
Feel free to test again and also test with only the two mods involved on your system.

**Comment by Desenrrollado** [comment]
This seems to have resolved it, and yeah I'm sure it was most likely that. I think I ended up disabling one or two mobs. Which was the golem variants. The issue I had was when you killed a mini golem at least in the original 1.12.2 release a floating block entity would be left to exist. I have no idea if this was ever patched or fixed. So it was more then likely a better safe then sorry scenario. 

Thank you so much in any case.

**Comment by xJon** [comment]
@Desenrrollado If you can reproduce the issues with the mobs you disabled, feel free to open a separate issue - they might be fixable.
