### ISSUE TITLE
Nerf weapons (or add config for it)

### ISSUE THREAD

**Issue by nocturni** [Elite-Modding-Team/MoCreaturesExtended#11]
Most weapons in the mod don't have delay when attacking, which makes them spammable. Tusks, scorpion swords and pretty much every other weapon is affected by this, breaking vanilla balance.

**Comment by IcarussOne** [comment]
I'll look at this for a future PR.

**Comment by ACGaming** [comment]
Implemented in 55575044e031d11cf33946230619d705c8d77e92.
