### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by nocturni** [Elite-Modding-Team/MoCreaturesExtended#12]
After doing a pull request on the wrong page, I'll just leave this here as an issue instead.

I made a French language that should follow french Minecraft's syntax and ways to name items and mobs.

https://pastebin.com/16hdr8Ug

Since I don't know how to do pull requests much, I'm leaving a pastebin here, it will work in-game if you make a lang file called fr_fr.

Please credit me if used :P

**Comment by IcarussOne** [comment]
I've included this on my current PR!

**Comment by ACGaming** [comment]
Implemented in 6b447457726e0e6680bde60434f1e9e0bd2de169.

**Comment by nocturni** [comment]
Annnd here's an update; https://pastebin.com/1hQLT7Sx.

Vocabulary was adapted to fit the new Wyvern dimension, added new entities, descriptions and everything.

Fixed some typos from the one I sent before.
