### ISSUE TITLE
creatures from Prehistoric Nature not spawn

### ISSUE THREAD

**Issue by ralseilii** [Elite-Modding-Team/MoCreaturesExtended#123]
every creature from Prehistoric Nature cannot spawn in prehistoric dimensions once after mocreature added ,using lepidodendron-1.12.2-51.4 and DrZharks-MoCreatures-Extended-12.3.1. Hoping for it be fixed since making modpack that contains these two mods.

**Comment by ralseilii** [comment]
but using lepidodendron-1.12.2-50.2 works normal,versions after that cannot spawn creatures with mocreatures

**Comment by ACGaming** [comment]
Duplicate of #78 either way.
