### ISSUE TITLE
Invalid generated weight

### ISSUE THREAD

**Issue by al-wei** [Elite-Modding-Team/MoCreaturesExtended#125]
Even if the value is adjusted very low, the amount generated is still very high.
DrZharks-MoCreatures-Extended-12.4.1
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/145486869/d42bce6a-cb06-4946-af07-9b01102faac2)
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/145486869/1b57f2ed-4e18-43f2-8cb2-8b816297872d)
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/145486869/55b5d7b9-4c1d-44f5-9bb6-7bf0421cfb9d)

**Comment by ACGaming** [comment]
Are these verifiable world-gen spawns or natural spawns?

**Comment by al-wei** [comment]
> Are these verifiable world-gen spawns or natural spawns?

Enter the game and see that there are many creatures.

**Comment by ACGaming** [comment]
Config toggles implemented in 879b301d3a9444493dfe98ef1106da90a8633a37
