### ISSUE TITLE
French translation³

### ISSUE THREAD

**Issue by nocturni** [Elite-Modding-Team/MoCreaturesExtended#127]
i still dont know how to do pull requests but here it is;

https://pastebin.com/kQSZeQqi

i fixed some syntax, an oversight for the mystic pear and i added all of the new items

i couldn't find a proper translation for Mattock so i went with "Pioche-pelle", which should be good enough?

also for the "[NYI]" tags, i translated them to "[ND]" which means "non disponible" (not available)

hopefully this is good enough!

lil note; i wish i could also translate more item descriptions like for the whips and the crystal mount armor

**Comment by IcarussOne** [comment]
No worries about not translating everything, you've been a real great help on the translation! :)

**Comment by nocturni** [comment]
no worries! i try to translate everything but it seems like it's not possible to translate some of the item descriptions, that's what i meant, the strings seem hardcoded (?)

**Comment by IcarussOne** [comment]
@nocturni
Odd have you checked the en_us file? It should have all the item descriptions there. If there are any specific ones that are still hardcoded they will be looked into.

**Comment by nocturni** [comment]
sorry for the late answer, usually I count how many lines there are compared to the en_us file to avoid missing any strings but it seems like it's syncing here, some item descriptions are there and some others aren't it seems
