### ISSUE TITLE
Fire Scorpion with babies will not spawn

### ISSUE THREAD

**Issue by gwynhefar** [Elite-Modding-Team/MoCreaturesExtended#128]
I'm using Mo Creatures Extended version 12.4.1 for Minecraft 1.12.2 but after tracking down and killing over 20 naturally spawning fire scorpions without encountering a single one carrying babies I decided to do an experiment and gave myself fire scorpion spawn eggs - I actually spawned over *300* scorpions from the spawn eggs and still not a single one carrying babies.  All the other scorpion types spawn with babies just fine, so I'm assuming it's some sort of bug.

**Comment by ACGaming** [comment]
In the current version, fire scorpions and undead scorpions don't spawn with babies as an incentive to utilize essences. We agreed in the team that it's not the best approach, so we added an egg-dropping mechanic for all scorpion types while making it more likely for mother scorpions to drop some in 778098e56d469023e8e06966f2acb51eaa56d98f.

**Comment by gwynhefar** [comment]
Awesome, thanks!  I was used to them spawning with babies in the original Mo Creatures so using essences felt like cheating :)
