### ISSUE TITLE
Craftable Saddle to be compatible with vanilla horses

### ISSUE THREAD

**Issue by xJon** [Elite-Modding-Team/MoCreaturesExtended#13]
Appears to be important as its name is suggestive to match the vanilla saddle features.

**Comment by ACGaming** [comment]
The vanilla saddle is hardcoded in six different places for vanilla horses, doubt this is easy to achieve without coremodding.

**Comment by IcarussOne** [comment]
The recent removal of the item should nullify this inconsistency. 👍
