### ISSUE TITLE
Kitties spawning *everywhere*

### ISSUE THREAD

**Issue by gwynhefar** [Elite-Modding-Team/MoCreaturesExtended#130]
So I started a new world, and for some reason the kitty mob is spawning in every biome, including the middle of the ocean

I have no idea what could be causing it, but here's my config for the kitty and as you see it should only be spawning in Plains and Forests. 

####################
# kitty
####################

kitty {
    S:biomeTypes=[PLAINS, FOREST]
    S:blockedBiomeTypes=[]
    B:canSpawn=true
    S:dimensions=[0]
    I:frequency=8
    I:maxSpawn=2
    I:minSpawn=1
}

![2024-03-15_00 56 09](https://github.com/ACGaming/MoCreaturesExtended/assets/3708692/379bad27-1210-4b80-8c8d-272897b86e57)

**Comment by IcarussOne** [comment]
Most likely related to #2, see if setting `KittyVillageChance` to `0` in `MoCSettings.cfg` stops this from happening.
