### ISSUE TITLE
Aquatic entities from other mods won't spawn (again)

### ISSUE THREAD

**Issue by NinetyKnight99** [Elite-Modding-Team/MoCreaturesExtended#131]
I have been doing more tests, I already removed all the mods, I already deleted all the configurations, I did tests without zawa, using only the abyssaldephts and better animal plus mods and the error persisted.

the creatures from these two mods do not spawn in the ocean, only the creatures from mo creatures,  and if I remove the mo creatures mod, the animals from better animal plus and abyssaldepths spawn again.

I don't know what happened that caused animals from other mods and mo creatures to appear at the same time during one of the tests, motive why I assumed the bug was from Zawa, but the bug returned again even without that mod.

so the bug is from mo creatures and not from zawa or some other mod in my modpack

**Comment by IcarussOne** [comment]
#126
