### ISSUE TITLE
Ogre heads DETACH and FLOAT in the air when looking up.

### ISSUE THREAD

**Issue by ssshadowed** [Elite-Modding-Team/MoCreaturesExtended#137]
Exactly what is said in the title, all the Ogre models break when they look up, the head detaches from the body and floats above it as it turns around and spins, it freaked me out when I saw my first ogre in the nether in my survival world. 

![image](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/bb83b49a-e80b-44e4-94e4-1964dd69966d)

**Comment by ACGaming** [comment]
Not applicable to our continuation of the mod.
