### ISSUE TITLE
Shark Issues 

### ISSUE THREAD

**Issue by ssshadowed** [Elite-Modding-Team/MoCreaturesExtended#138]
**SPAWNING**

Sharks in the recreation of this wonderful mod are _not_ like the sharks we know of the original mod.

These sharks ONLY spawn in river biomes, which shouldn't be that way, what's even worse is they don't spawn in the ocean AT ALL from my knowledge of extensive searching and looking.

Screenshots of oceans showcasing no sharks anywhere 

![2024-04-15_01 51 15](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/d751101d-8ee5-4e0c-bbf0-bc30ba4498b8)
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/d6644565-ef06-4b98-8f93-04bc8914ff5e)

a river biome, where they have been only shown
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/8c373b24-2b00-4740-9111-e5638df0f175)

---

**SIZE**

Sharks only appear in one size, small. Sharks in this mod are a tiny, baby-like size compared to what the old mod was, if this is able to be improved, could we get multiple sizes of sharks ? Many species of shark exist, coral reef sharks which are usually small all the way to big sharks like hammerhead sharks or great white sharks. Currently, the shark model is smaller than the dolphin model.

---

**MOVEMENT

Sharks move really weirdly, they are slow-moving, don't move at all on land, and get stuck in place unless pushed if they are in 1 block  high water no matter how much water is around them.

---

I really appreciate this timeless mod being brought back and updated, I loved it in my childhood and loved watching YouTuber mod packs with it, I will try my hardest to give feedback to improve this mod for all time.

**Comment by ACGaming** [comment]
Not applicable to our continuation of the mod.
