### ISSUE TITLE
Water Creatures Issue

### ISSUE THREAD

**Issue by ssshadowed** [Elite-Modding-Team/MoCreaturesExtended#139]
![2024-04-15_02 14 44](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/c1c84c2f-6ccc-421e-ae56-7813cb1d7605)

All current water creatures in the mod stop moving completely if out of water or in 1 block high water, they also **DON'T DIE !** 
Unlike current vanilla fishes, all go on their side and flop around looking for water, after a while they start taking damage until they die. This does not happen in this mod, when it did happen in the old version of the mod !

---

Stingrays and Mantarays are only SALT WATER marine animals, they should stop spawning in rivers and freshwater lakes, same as sharks ! Please bring them to the oceans.

--- 

Stingrays don't have to attack you to apply poison to you 
In the old version, if you attacked a stingray, it would attack back, applying poison to you. In this version of the mod, if you so much as just look at them up close, you get poisoned ! That is not supposed to happen, it happens even in Creative !

![2024-04-15_01 58 48](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/52259ef2-630e-499d-8331-038b45035f1c)

---

Pink / Rare Dolphins are as common as normal dolphins, this shouldn't be the case ! Make rare mobs rare again !

![2024-04-15_02 02 44](https://github.com/ACGaming/MoCreaturesExtended/assets/167039313/f8eb9cbe-5aa9-42db-9a8f-84787dd5379c)

**Comment by ACGaming** [comment]
Not applicable to our continuation of the mod.
