### ISSUE TITLE
Scorpion Swords render in hand incorrectly

### ISSUE THREAD

**Issue by xJon** [Elite-Modding-Team/MoCreaturesExtended#14]
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/8945347/530f09f3-53dd-4060-8a5e-bc4ba5ab613f)

**Comment by IcarussOne** [comment]
@xJon
This actually applies to all the tools, it can be fixed by changing the parent in their item model json from 'item/generated' to 'item/handheld'.

**Comment by ACGaming** [comment]
Implemented in ec83f7051932541b4fd691da0dd5a9db6ebb0a75.
