### ISSUE TITLE
Getting Bunny off player head can move Bunny into block, causing them suffocate to death

### ISSUE THREAD

**Issue by xJon** [Elite-Modding-Team/MoCreaturesExtended#148]
Specifically vertical blocks, e.g. a house wall from the inside.

**Comment by xJon** [comment]
It is also possible to push a Bunny into a non-full block in which they, once again, suffocate to death.

**Comment by demonlexe** [comment]
I also experienced a crash when a bunny dies which may be related to this-- looking now
