### ISSUE TITLE
Sharks and boats

### ISSUE THREAD

**Issue by SromFunnyBoi** [Elite-Modding-Team/MoCreaturesExtended#156]
I noticed that when sailing on a boat sharks can't do anything to the player and that's fine, but I thought about sharks being able to destroy the boat. In the sense that not immediately, but if they "bite" it for some time. Just like when the player wants to destroy it with his hand.

**Comment by xJon** [comment]
Can also have a chance of being able to hit the player in the boat, or kicking the player out of the boat.

**Comment by SromFunnyBoi** [comment]
Well, I was thinking about a simpler solution xD but if you want to play with something more complex, it's even better.
However, I'm not too convinced that they could throw the player out of the boat. I think that destroying the boat would be enough, but it's your creativity and you can do whatever you want. ¯\_(ツ)_/¯
