### ISSUE TITLE
Giving Mo' Creatures' horses the ability to crossbreed with vanilla horses

### ISSUE THREAD

**Issue by IcarussOne** [Elite-Modding-Team/MoCreaturesExtended#16]
This is a common suggestion I see a lot and I'm not sure how possible it is to do it, but it would be interesting to see something like this and possibly expand the types of horse breeds you can obtain.

**Comment by nocturni** [comment]
Isn't it already the case of needing to breed mo' creatures horses with vanilla ones?

**Comment by ACGaming** [comment]
Kind of forgot about this but yes, support for cross-breeding is already included.
More about this here: https://mocreatures.fandom.com/wiki/Horse#Breeding

**Comment by IcarussOne** [comment]
Huh, I could have sworn it wasn't a feature... Thanks for letting me know about this!
