### ISSUE TITLE
Different horse types should be split into their own entities

### ISSUE THREAD

**Issue by IcarussOne** [Elite-Modding-Team/MoCreaturesExtended#17]
Vanilla horse types are all their own separate mob, a past update also had split up the vanilla zombie/skeleton variants into their own mobs, so I think splitting the horses will allow easier control on where each type can be spawned or obtained especially for modpack makers, but at the same time it would most likely require a rework of how horses work and it is quite a big list of new mobs to add in.

**List of types:**
-Bat Horse
-Default Horse
-Donkey
-Fairy Horse
-Fire Horse
-Ghost Horse (flying one as well maybe?)
-Mule
-Pegasus
-Skeleton Horse (possibly unicorn and pegasus variants too)
-Unicorn
-Zebra
-Zombie Horse (possibly unicorn and pegasus variants too)
-Zonkey
-Zorse

**Comment by xJon** [comment]
Just a note, some of these horses don't spawn on their own but are a special breed (similarly to vanilla Mules) or require a special item to be used.

**Comment by ACGaming** [comment]
Either way, as this would require a rewrite of horse breeding, this is going to be considered at the far end of the line.

**Comment by IcarussOne** [comment]
Closing in favor of #144.
