### ISSUE TITLE
Undead/fire/darkness Hearts wont drop

### ISSUE THREAD

**Issue by Blurr276** [Elite-Modding-Team/MoCreaturesExtended#173]
I have tested this on popular versions and on the lastest version
For some reason, no matter what level of looting I have, no heart will drop. Ever. Ive been testing this for a couple hours and no hearts have dropped. Is there an option in the config that im missing? or something?

**Comment by demonlexe** [comment]
Working on this! Thanks for reporting! It does look like the drop rates are very low in the loot table and I am working to adjust this.
