### ISSUE TITLE
It is possible to push a Bunny into a non-full block in which they suffocate to death.

### ISSUE THREAD

**Issue by demonlexe** [Elite-Modding-Team/MoCreaturesExtended#178]
It is also possible to push a Bunny into a non-full block in which they, once again, suffocate to death.

_Originally posted by @xJon in https://github.com/Elite-Modding-Team/MoCreaturesExtended/issues/148#issuecomment-2099627587_

I fear this may be a hit-box related thing, will need to revisit this separately

**Comment by xJon** [comment]
Tested the latest build with #177 and I can't reproduce this issue, so closing for now!
