### ISSUE TITLE
Too many kitties

### ISSUE THREAD

**Issue by juraj-hrivnak** [Elite-Modding-Team/MoCreaturesExtended#2]
They spawn too often and in every biome, even in the ocean.

MoCreaturesExtended version: `12.1.0`

**Comment by ACGaming** [comment]
Not able to reproduce this, are you testing in a vanilla setting?

**Comment by juraj-hrivnak** [comment]
No, I have a bunch of mods. I will try to find the mod conflict and let you know.

**Comment by ACGaming** [comment]
Would be great, thanks!

**Comment by juraj-hrivnak** [comment]
Still didn't find the mod conflict, but at least I made some progress.
I set the `KittyVillageChance` to `0`, and it fixed the issue.

**Comment by ACGaming** [comment]
Alright, might be related to mods changing village structures then! We leave this open for now.

**Comment by xJon** [comment]
A mod making every chunk count as a village? 💀
