### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by Intipablo** [Elite-Modding-Team/MoCreaturesExtended#23]
Thanks for the much needed maintenance of this amazing mod.
I'm crashing in the latest version of the mod in my personal modpack when right-clicking on a flying Manticore, and I think it crashes on other occasions too so it might be my mistake and another mod in the pack but here is the report.

[crash-2023-06-10_01.20.53-server.txt](https://github.com/ACGaming/MoCreaturesExtended/files/11707736/crash-2023-06-10_01.20.53-server.txt)

EDIT: it just now happened upon loading my world instantly.

[crash-2023-06-10_01.25.21-server.txt](https://github.com/ACGaming/MoCreaturesExtended/files/11707774/crash-2023-06-10_01.25.21-server.txt)

**Comment by ACGaming** [comment]
Can you test if it‘s no longer crashing with [this build](https://github.com/ACGaming/MoCreaturesExtended/suites/13496169423/artifacts/741314134)?

**Comment by Intipablo** [comment]
The new build is working perfect but I actually can't reproduce the crash with the old version anymore because I've since deleted the world and some other mods. Either way my games not crashing anymore so 👍

**Comment by ACGaming** [comment]
Great news! The change I made concerning this issue should fix this edge case in the future.
