### ISSUE TITLE
Golem sometimes leaves blocks stuck in the air

### ISSUE THREAD

**Issue by nocturni** [Elite-Modding-Team/MoCreaturesExtended#33]
I am unsure how these golems made out of blocks are called but sometimes they leave blocks stuck in the air, it's impossible to remove them so they're just stuck entities.

**Comment by ACGaming** [comment]
Already fixed for the upcoming release: https://github.com/ACGaming/MoCreaturesExtended/blob/b55ac0baa15abc0130701d824e8a3f426f91c84b/src/main/java/drzhark/mocreatures/entity/item/MoCEntityThrowableRock.java#L117
