### ISSUE TITLE
Crash with Minor Integrations and Additions

### ISSUE THREAD

**Issue by Sereath** [Elite-Modding-Team/MoCreaturesExtended#36]
This happened today when I updated to 12.1.1
https://gist.github.com/Sereath/39205d9da76ffe18824c93c492660a9f

I can see that it is because of [MIA](https://www.curseforge.com/minecraft/mc-mods/minor-integrations-and-additions-mia) wanting to work with a very old version of Mo‘ Creatures, so not sure if anything could be done.

**Comment by Sereath** [comment]
Disabling Thermal's integration stops it from crashing.
```
    B:"Enable Thermal Expansion integration"=false
```
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/54506307/82f3c573-cceb-4484-9b48-42e2f6771020)

I'm now wondering if I should just disable everything else.

**Comment by ACGaming** [comment]
We discussed the matter and made the decision to implement a certain amount of MIA‘s Mo‘ Creatures integration natively. Stay tuned!

**Comment by ACGaming** [comment]
Since we have implemented third party mod support for HarvestCraft, Thaumcraft, Thermal Expansion, Future MC, Industrial Foregoing and Morph for the upcoming update, you‘ll be able to turn these config settings off without missing out on compatibility.

**Comment by IcarussOne** [comment]
The changes to silver weapons and item replacements for the fish are also no longer needed since both features are in the mod already. Any mod that tweaks loot tables can be used to further adjust their drops now, so I would keep both of those turned off in the config.
