### ISSUE TITLE
Feeding Baby Horses Growth Glitch

### ISSUE THREAD

**Issue by SilentStarling** [Elite-Modding-Team/MoCreaturesExtended#40]
Hello! This has been a long-complained-about bug and it would be awesome if you guys could rectify it. 

When a baby Moc horse is fed to make it grow faster, it turns it into a "permanent baby". Even though it grows to full size, it still functions like a baby horse, in that it cannot be saddled, rode, or bred. Nobody I know of has been able to fix it in-game; the horse just stays broken forever. The only solution we had was to not force feed baby horses. Since vanilla horses can be force fed to grow faster, it would be awesome if this would work for Moc horses as well. Thanks!

**Comment by ACGaming** [comment]
Fixed with 5686ca9c4819c09caa1a3562d2b852eebee3d588.
