### ISSUE TITLE
Hitboxes do not match mob models

### ISSUE THREAD

**Issue by SromFunnyBoi** [Elite-Modding-Team/MoCreaturesExtended#47]
Some of the most noticeable examples:
![1](https://github.com/ACGaming/MoCreaturesExtended/assets/98231778/48c72b2d-849f-4ca7-94f9-026a4ee2e54f)
![2](https://github.com/ACGaming/MoCreaturesExtended/assets/98231778/6385ebcd-6874-42de-a1a3-048ed88c6f34)
![3](https://github.com/ACGaming/MoCreaturesExtended/assets/98231778/7d8547cb-f837-43c4-9087-fe485665d8f1)
![5](https://github.com/ACGaming/MoCreaturesExtended/assets/98231778/1efedc21-7864-4251-80cc-048f7d6cd168)
![4](https://github.com/ACGaming/MoCreaturesExtended/assets/98231778/d6d1b70d-d88b-47ae-8026-ac95b0436de5)

**Comment by SromFunnyBoi** [comment]
Btw ants have 20hp while rest of the bugs have 4

**Comment by IcarussOne** [comment]
The health and hitbox issues of the ants have been fixed, as well as the rest of the ambient mobs. All other hitbox problems will be fixed over time.

**Comment by IcarussOne** [comment]
The majority of hitboxes have been taken care of now including all the worst ones shown above. They currently do not adjust with growth but that is a separate issue that will be looked into in the future.
