### ISSUE TITLE
A 1.7 continuation would be nice.

### ISSUE THREAD

**Issue by MagmaSlime123** [Elite-Modding-Team/MoCreaturesExtended#6]
Title. Doubt this would be considered, but I'd though I'd pop this in here.

**Comment by xJon** [comment]
See https://github.com/jss2a98aj/mocreaturesdev/releases for a 1.7.10 continuation.

**Comment by MagmaSlime123** [comment]
That was a year and a half ago.

**Comment by ACGaming** [comment]
> That was a year and a half ago.

Still worth giving it a try though!

As I hardly have any 1.7 modding experience, won‘t happen from our side I‘m afraid.
