### ISSUE TITLE
Server side Exception Log Spamming

### ISSUE THREAD

**Issue by Ldawsonm** [Elite-Modding-Team/MoCreaturesExtended#64]
I'm getting this exception in my server's log: 
`java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
     at drzhark.mocreatures.entity.MoCEntityAnimal.getName(MoCEntityAnimal.java:81) ~[MoCEntityAnimal.class:?]`
This exception is not fatal, it's just spamming my logs since java loves to give you the entire error message, even the unhelpful parts. I went into the source code and it looks like on line 16 of MoCEntityAnimal.java, there is an import for net.minecraft.client.resources.l18n

I am not at all familiar with the code base, and given my frequent posting of issues and the fact that I know java fairly well, I feel like I should start getting familiar with the code base and making pull requests instead of coming on here and going "Devs! Fix this!" especially since this is not a fatal issue.

Anyway, just thought I'd make aware this issue. Thanks!

**Comment by IcarussOne** [comment]
Bug reports are always appreciated, no worries about how minimal it is. Feel free to make pull requests any time!
