### ISSUE TITLE
Mini Golem problems

### ISSUE THREAD

**Issue by SromFunnyBoi** [Elite-Modding-Team/MoCreaturesExtended#66]
here's a video for better visualization:

https://github.com/ACGaming/MoCreaturesExtended/assets/98231778/2f429d3d-95c8-4dbf-81bd-4c1c60afd474

- Blocks that mobs throw disappear too quickly
- If a Mini Golem picks up a torch, lever, button, etc. or even a top slab, it results in an item with no model or texture
- When a mob is holding a block and stops being aggressive, it releases it and keeps its hands up anyway

There is one more bug that you can notice, it's visual and it's not very disturbing but the texture of the mob sometimes blink from aggressive to passive

**Comment by TheMagicalSC** [comment]
I've noticed that this happens with items that are dropped by the big golem too.
