### ISSUE TITLE
Big Golem often takes a long time to obtain blocks

### ISSUE THREAD

**Issue by Turkey9002** [Elite-Modding-Team/MoCreaturesExtended#7]
It usually takes almost a minute or longer for a big golem to complete itself. Blocks can get stuck too and end up just staying there for awhile.

Making the process go faster and having blocks not get stuck would be great. Adding physics to blocks and configuring what type of blocks the golems can take (to prevent mass house destruction) or what blocks is used for the core like the metal blocks would be nice too.

**Comment by ACGaming** [comment]
Block acquirement is now vastly improved and works like originally intended. More configurability might be introduced later on.
