### ISSUE TITLE
New Hell Rat sounds not playing when on a server

### ISSUE THREAD

**Issue by Frosto23** [Elite-Modding-Team/MoCreaturesExtended#70]
Thank you for maintaining this very cool old mod by the way.
They play the sounds in the single player mode but on a server it doesn't play any sound at all.

Edit: I tried just with having Mo'creatures jar file on both server and client, still no sound.

**Comment by IcarussOne** [comment]
Sorry about that, it was an oversight on my part. Thanks for the report!
