### ISSUE TITLE
French language²

### ISSUE THREAD

**Issue by nocturni** [Elite-Modding-Team/MoCreaturesExtended#72]
Annnd here's an update; https://pastebin.com/1hQLT7Sx

Vocabulary was adapted to fit the new Wyvern dimension, added new entities, descriptions and everything.

Fixed some typos from the one I sent before.

**Comment by nocturni** [comment]
Accidentally reopened an issue when trying to open the old one :S

**Comment by IcarussOne** [comment]
Got this in for you, thanks for your hard work!

**Comment by nocturni** [comment]
no worries!

I'm gonna work on an updated version soon for the latest update.
