### ISSUE TITLE
Entities from other mods won't spawn

### ISSUE THREAD

**Issue by ralseilii** [Elite-Modding-Team/MoCreaturesExtended#78]
It will cause a disturbance in the generation of Glacidus' dimensional creatures (those originally supposed to generate in the second layer will generate in the first layer instead, leading to their death). Besides, it will result in the failure of prehistoricspawns' spawning of dinosaurs of Fossils and Archeology Revival mod(i need prehistoricspawns feature most but it cannot work with mocreature extend )

**Comment by ralseilii** [comment]
and i think it spawns too many passive creatures which causes few hostile creatures on the ground when night

**Comment by ACGaming** [comment]
This was improved in the latest commit, Mo‘ Creatures Extended should no longer modify other mods‘ spawns. You can fetch it here to test: https://github.com/ACGaming/MoCreaturesExtended/suites/16963301251/artifacts/969192456
Keep in mind you need to extract the archive.

Concerning too many creatures, please note that the config value `SpawnMultiplier` in `MoCSettings.cfg` is a mighty tool for this.

**Comment by ralseilii** [comment]
Thank you, but I feel that when DrZharks-MoCreatures-Extended-12.4.0 and prehistoricspawns-2.1 are installed together, prehistoricspawns still does not spawn dinosaurs. When I remove DrZharks-MoCreatures-Extended-12.4.0, it works fine. (Also happens with Glacidus )Additionally, it seems that I am unable to tame kitties and BigCats in the latest version.

**Comment by ACGaming** [comment]
Thanks for the feedback, we‘ll test accordingly.

**Comment by caioraphael1** [comment]
I'm also having the same problem with the mod Exotic Birds. The birds stop spawning with I use the mods with Mo'Creatures. Using the v12.4.0 didn't fix the problem, just increased the the amount of animals spawning from Mo'Creatures by a LOT.

**Comment by caioraphael1** [comment]
Some feedback on v12.4.0: I'm using Animania Extras, Animania Farm, Better Animals Plus, Bewitchment, and Mo'creatures Extended v12.4.0, but only mobs from Mo'creatures spawns if I use Mo'creatures. I tried lowering the spawnMultiplier in the MoCSetting.cfg from 2.0 to 0.2, but even tho the number of creatures from Mo'creatures decreased by a lot, creatures from other mods still didn't spawn. Then I tried disabling the spawn of every creature from Mo'creature, by changing the 'canSpawn' to 'false' to every single one of them, so finally the other mobs started spawning, but obviously, no mo'creature entity spawned. The ACTUAL only way I found to make all mods co-exist was to keep 'canSpawn=false' to all Mo'creatures entities but use InControl to manually set the spawn accordingly, which sucks, as I have to manually set the spawn for every single creature while trying to guess the best values for balancing.

**Comment by ACGaming** [comment]
Did another test run with the current state of the Mo‘ Creatures codebase along with Animania + all of its add-ons and Better Animals Plus, all with default configs. I could witness entities spawning from all three mods, even in spawn vicinity. It appears the latest changes to the spawning logic did indeed fix apparent spawning issues in connection with other mods.

**Comment by ralseilii** [comment]
could you send the dev that has fixed this kind of spawning issue please

**Comment by ralseilii** [comment]
will you send a fixed dev version for modpack test ,thank you

**Comment by AdamBenabouTCR** [comment]
I've found other mod that Mo creatures has the issue, this being with tinkers' construct. Blue Slimes won't spawn on Slime Islands but when I remove Mo creatures they're able to spawn.
