### ISSUE TITLE
MIA crash

### ISSUE THREAD

**Issue by Sereath** [Elite-Modding-Team/MoCreaturesExtended#79]
Just today I updated from 12.1.1 to 12.3.1:

https://mclo.gs/wLGmJjj

Seconds after loading a new world.

And I had already disabled all of MIA's Mo Creatures settings:
![image](https://github.com/ACGaming/MoCreaturesExtended/assets/54506307/e8566a3c-1367-4e73-a454-d44fe5d4a8ef)

**Comment by ACGaming** [comment]
Thanks for the report, already fixed for the upcoming update!
