### ISSUE TITLE
Wyverns not dropping eggs

### ISSUE THREAD

**Issue by RibozymeC** [Elite-Modding-Team/MoCreaturesExtended#80]
Wyverns do not drop eggs in version 12.3.2 used in Hexxit II.

**Comment by IcarussOne** [comment]
We will definitely look into fixing this for the next update.

**Comment by RibozymeC** [comment]
Thank you!

For info until then: Hatching wyvern eggs still works the same, since the overhaul isn't happening yet, yes?

**Comment by IcarussOne** [comment]
It is indeed very likely that they will receive their overhaul in the next update. :)
