### ISSUE TITLE
[Suggestion] Configurable Filch Lizard Held Items

### ISSUE THREAD

**Issue by Handeril** [Elite-Modding-Team/MoCreaturesExtended#83]
As it says in the topic, would it be possible to make what Filch Lizards sometimes spawn with configurable?

I think this could be a nice feature to play around with - especially in large modpacks.

**Comment by IcarussOne** [comment]
It is actually possible to customize the Filch Lizard item spawns with a loot table editor, you can find the **filch_lizard** folder inside the entity loot tables folder. A config option can also be looked into if there's demand for it. :)

**filch_lizard_spawn** controls what items the lizards spawn with. You can control the chance for a lizard to spawn with an item in the config (25% chance by default).
**filch_lizard_steal** controls what items the lizards are interested in stealing.
**filch_lizard** controls drops for when a lizard is killed (currently empty for now).

**Comment by xJon** [comment]
You can find an example of adding custom loot to it with [LootTweaker](https://www.curseforge.com/minecraft/mc-mods/loottweaker) in [Hexxit II](https://www.technicpack.net/modpack/hexxit-ii/)'s `\scripts\loot\hexxit_loot_changes.zs` L#35.
