### ISSUE TITLE
mo' creatures extended + zawa

### ISSUE THREAD

**Issue by BegoR67** [Elite-Modding-Team/MoCreaturesExtended#84]
During the use of two mods, mobs from zawa stop appearing
zawa-1.12.2-2.1.3
DrZharks-MoCreatures-Extended-12.3.1
UniversalTweaks-1.12.2-1.8.0

**Comment by IcarussOne** [comment]
Spawn issues with third party mods are currently being investigated. You can read more about it in issue #78.

**Comment by IcarussOne** [comment]
Closing this because it is already being tracked on the issue number mentioned above.
