### ISSUE TITLE
Crafting Saddles with Leather

### ISSUE THREAD

**Issue by Sloth627** [Elite-Modding-Team/MoCreaturesExtended#89]
In the original mod I used to be able to craft saddles with leather or hide but it will only craft with hide now, which is pretty annoying because boars aren't breedable.

**Comment by Sloth627** [comment]
Just realized boars drop leather now so I have to hunt bears to get hide

**Comment by IcarussOne** [comment]
We decided it was better off to just remove the crafted saddle completely (for compatibility reasons) and replace it with a configurable crafting recipe for the vanilla saddle. The recipe requires leather again like how it was originally intended, you can also get leather from hide and reptile hide.
