### ISSUE TITLE
right clicking a tamed Kitty with a Pet Amulet will drop a second Medallion

### ISSUE THREAD

**Issue by nocturni** [Elite-Modding-Team/MoCreaturesExtended#91]
title, using the Pet Amulet on a Kitty makes it drop a medallion while it is wearing one, making it duplicate medallions

**Comment by demonlexe** [comment]
Do we close this once dev is merged ?

**Comment by IcarussOne** [comment]
@demonlexe
We close fixed issues as soon as the new version is released. :)
