### ISSUE TITLE
Big Cats follow their owner inconsistently

### ISSUE THREAD

**Issue by demonlexe** [Elite-Modding-Team/MoCreaturesExtended#98]
# Steps to reproduce
Tame a `BigCat`. Observe that it follows the player a lot, probably more than it should.

**Comment by ACGaming** [comment]
Unrelated to the whip, `EntityAIFollowOwnerPlayer` and its priority within `MoCEntityBigCat` need to get investigated though.

**Comment by demonlexe** [comment]
I did look at `EntityAIFollowOwnerPlayer`, it has the lowest priority of the AI events, but it still doesn't have an activator with `rand(500) == 0` like the other AI events like `AIEntityHunt` do--- if it falls through to`EntityAIFollowOwnerPlayer`, it just consistently runs
